# render.yaml
# Blueprint for deploying the multi-service Rok-AI application

# Define Environment Groups for shared secrets and configurations
# Replace placeholder values with your actual secrets in the Render Dashboard.
envVarGroups:
  - name: common-db-config
    envVars:
      - key: MONGODB_URI
        value: "YOUR_MONGODB_ATLAS_CONNECTION_STRING_HERE" # IMPORTANT: Replace with your actual MongoDB Atlas URI
  - name: alpaca-api-keys
    envVars:
      - key: ALPACA_API_KEY # Used by executor-day (and daytrade_genie.py)
        value: "YOUR_ALPACA_API_KEY_FOR_DAYTRADE_HERE"
      - key: ALPACA_SECRET_KEY # Used by executor-day (and daytrade_genie.py)
        value: "YOUR_ALPACA_SECRET_KEY_FOR_DAYTRADE_HERE"
      - key: ALPACA_SCALPINGSNIPER_KEY # Used by executor-swing
        value: "YOUR_ALPACA_SCALPINGSNIPER_KEY_HERE"
      - key: ALPACA_SCALPINGSNIPER_SECRET_KEY # Used by executor-swing
        value: "YOUR_ALPACA_SCALPINGSNIPER_SECRET_KEY_HERE"
      - key: ALPACA_UNHOLY_KEY # Used by executor-options
        value: "YOUR_ALPACA_UNHOLY_KEY_HERE"
      - key: ALPACA_UNHOLY_SECRET_KEY # Used by executor-options
        value: "YOUR_ALPACA_UNHOLY_SECRET_KEY_HERE"
  - name: other-api-keys
    envVars:
      - key: OPENAI_API_KEY # Used by router
        value: "YOUR_OPENAI_API_KEY_HERE"
      - key: FINNHUB_API_KEY # Used by scanners (daytrade_genie.py) and executor-day (alpaca_day.py)
        value: "YOUR_FINNHUB_API_KEY_HERE"
      - key: Slcaper_Stock_TELEGRAM_BOT_TOKEN # Typo from alpaca_swing.py, should be Scalper_Stock_...
        value: "YOUR_SCALPER_TELEGRAM_BOT_TOKEN_HERE" # Check original file for correct name
      - key: TELEGRAM_CHAT_ID # Used by alpaca_swing.py
        value: "YOUR_TELEGRAM_CHAT_ID_HERE"
      - key: Unholy_TELEGRAM_BOT_TOKEN # Used by alpaca_options.py
        value: "YOUR_UNHOLY_TELEGRAM_BOT_TOKEN_HERE"
      - key: TELEGRAM_USER_ID # Used by alpaca_options.py
        value: "YOUR_UNHOLY_TELEGRAM_USER_ID_HERE"

services:
  - name: webapi # Your FastAPI backend
    type: web
    env: docker
    # repo: line removed - Render will use the repo connected at the Blueprint level
    region: frankfurt
    plan: standard
    dockerfilePath: ./web_api/Dockerfile
    healthCheckPath: /health # From your web_api/app.py
    envVars:
      - fromGroup: common-db-config
    autoDeploy: yes

  - name: scanners # Your scanners service
    type: worker
    env: docker
    region: frankfurt
    plan: standard
    dockerfilePath: ./scanners/Dockerfile # This Dockerfile should CMD ["python", "daytrade_genie.py"]
    envVars:
      - fromGroup: common-db-config
      - fromGroup: alpaca-api-keys # Assuming daytrade_genie needs the primary Alpaca keys
      - fromGroup: other-api-keys # For FINNHUB_API_KEY
    autoDeploy: yes

  - name: router # Your meta_ai service
    type: worker
    env: docker
    region: frankfurt
    plan: standard
    dockerfilePath: ./meta_ai/Dockerfile # This Dockerfile should CMD ["python", "strategy_router.py"]
    envVars:
      - fromGroup: common-db-config
      - fromGroup: other-api-keys # For OPENAI_API_KEY
      - key: USE_OPENAI # As per your docker-compose.yml
        value: "false" # Set to "true" if you want to use OpenAI and have the key
    autoDeploy: yes

  - name: executor-day
    type: worker
    env: docker
    region: frankfurt
    plan: standard
    dockerfilePath: ./executors/Dockerfile # Shared Dockerfile for executors
    envVars:
      - fromGroup: common-db-config
      - fromGroup: alpaca-api-keys
      - fromGroup: other-api-keys # For FINNHUB_API_KEY
      - key: ROLE
        value: "daytrade" # As per your docker-compose.yml
      - key: EXECUTOR_SCRIPT
        value: "alpaca_day.py"
    autoDeploy: yes

  - name: executor-swing
    type: worker
    env: docker
    region: frankfurt
    plan: standard
    dockerfilePath: ./executors/Dockerfile # Shared Dockerfile for executors
    envVars:
      - fromGroup: common-db-config
      - fromGroup: alpaca-api-keys
      - fromGroup: other-api-keys # For Telegram keys
      - key: ROLE
        value: "swing" # As per your docker-compose.yml
      - key: EXECUTOR_SCRIPT
        value: "alpaca_swing.py"
    autoDeploy: yes

  - name: executor-options
    type: worker
    env: docker
    region: frankfurt
    plan: standard
    dockerfilePath: ./executors/Dockerfile # Shared Dockerfile for executors
    envVars:
      - fromGroup: common-db-config
      - fromGroup: alpaca-api-keys
      - fromGroup: other-api-keys # For Telegram keys
      - key: ROLE
        value: "options" # As per your docker-compose.yml
      - key: EXECUTOR_SCRIPT
        value: "alpaca_options.py"
    autoDeploy: yes